// Builds the ZecPad logo from one source of truth:
// - outlines the "ZecPad" wordmark from Outfit 600 (opentype.js), so the logo never depends on a web font
// - writes src/components/brand/brand-geometry.ts (used by the React components)
// - writes public/brand/logo.svg, logo-light.svg, logo-500.png, logo-500-transparent.png and public/favicon.svg
// Run: npm run brand
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import opentype from 'opentype.js';
import { Resvg } from '@resvg/resvg-js';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const fontFile = path.join(root, 'node_modules/@fontsource/outfit/files/outfit-latin-600-normal.woff');

// Design tokens (keep in sync with src/styles/tokens.css)
const GOLD = '#F5B83D';
const INK = '#15130F';
const WHITE = '#FFFFFF';

// ---------- mark: a Z built from a launch ----------
// Bottom stroke = the pad, diagonal = the launch path, and a ZEC coin in place of the Z's top bar.
// 40 x 40 grid, tile radius 10 (matches the UI's rounded cards), stroke 4.2 with round caps.
const MARK = {
  size: 40,
  radius: 10,
  stroke: 4.2,
  glyph: ['M10 30H30', 'M10 30L20.4 19.6'],
  coin: { cx: 28, cy: 12, r: 5 },
};

// ---------- wordmark ----------
const buf = fs.readFileSync(fontFile);
const font = opentype.parse(buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength));
const TEXT = 'ZecPad';
const FONT_SIZE = 100;
const TRACKING = -0.02 * FONT_SIZE; // -2% tracking

let x = 0;
const parts = [];
// charToGlyph (not stringToGlyphs): the wordmark needs no ligatures, and it skips GSUB lookups opentype.js can't read
const glyphs = [...TEXT].map((ch) => font.charToGlyph(ch));
glyphs.forEach((g, i) => {
  const p = g.getPath(x, 0, FONT_SIZE);
  parts.push(p);
  let adv = (g.advanceWidth / font.unitsPerEm) * FONT_SIZE;
  if (i < glyphs.length - 1) adv += (font.getKerningValue(g, glyphs[i + 1]) / font.unitsPerEm) * FONT_SIZE;
  x += adv + TRACKING;
});
const merged = new opentype.Path();
parts.forEach((p) => merged.extend(p));
const bb = merged.getBoundingBox();
// normalise so the bbox starts at 0,0
const norm = new opentype.Path();
for (const c of merged.commands) {
  const n = { ...c };
  for (const k of ['x', 'y', 'x1', 'y1', 'x2', 'y2']) {
    if (k in n) n[k] = +(n[k] - (k.startsWith('x') ? bb.x1 : bb.y1)).toFixed(2);
  }
  norm.commands.push(n);
}
const WORD = { d: norm.toPathData(2), w: +(bb.x2 - bb.x1).toFixed(2), h: +(bb.y2 - bb.y1).toFixed(2) };

// ---------- lockup geometry (mark 40 tall, wordmark scaled to 24 units tall incl. ascenders) ----------
const wordH = 24;
const wordScale = wordH / WORD.h;
const gap = 10;
const lockupW = MARK.size + gap + WORD.w * wordScale;
const lockupH = MARK.size;
const wordY = (lockupH - wordH) / 2 + 1; // optical nudge: descender-free word sits a touch low

function markSvg(tile, ink) {
  return (
    `<rect width="${MARK.size}" height="${MARK.size}" rx="${MARK.radius}" fill="${tile}"/>` +
    `<g fill="none" stroke="${ink}" stroke-width="${MARK.stroke}" stroke-linecap="round" stroke-linejoin="round">` +
    MARK.glyph.map((d) => `<path d="${d}"/>`).join('') +
    `</g>` +
    `<circle cx="${MARK.coin.cx}" cy="${MARK.coin.cy}" r="${MARK.coin.r}" fill="${ink}"/>`
  );
}

function lockupSvg({ wordColor, tile = GOLD, ink = INK, bg, pad = 0, square = false }) {
  const w = lockupW + pad * 2;
  const h = square ? w : lockupH + pad * 2;
  const oy = square ? (w - lockupH) / 2 : pad;
  return (
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${w.toFixed(2)} ${h.toFixed(2)}" width="${w.toFixed(2)}" height="${h.toFixed(2)}">` +
    (bg ? `<rect width="100%" height="100%" fill="${bg}"/>` : '') +
    `<g transform="translate(${pad} ${oy.toFixed(2)})">` +
    markSvg(tile, ink) +
    `<path transform="translate(${MARK.size + gap} ${wordY.toFixed(2)}) scale(${wordScale.toFixed(5)})" fill="${wordColor}" d="${WORD.d}"/>` +
    `</g></svg>`
  );
}

const out = (p, s) => {
  fs.mkdirSync(path.dirname(p), { recursive: true });
  fs.writeFileSync(p, s);
};

// geometry module for React
out(
  path.join(root, 'src/components/brand/brand-geometry.ts'),
  `// Generated by scripts/build-brand.mjs. Do not edit by hand.\n` +
    `export const MARK = ${JSON.stringify(MARK)} as const;\n` +
    `export const WORDMARK = ${JSON.stringify(WORD)} as const;\n` +
    `export const LOCKUP = ${JSON.stringify({ w: +lockupW.toFixed(2), h: lockupH, gap, wordScale: +wordScale.toFixed(5), wordY: +wordY.toFixed(2) })} as const;\n`,
);

// public brand files
const brandDir = path.join(root, 'public/brand');
out(path.join(brandDir, 'logo.svg'), lockupSvg({ wordColor: WHITE }));
out(path.join(brandDir, 'logo-light.svg'), lockupSvg({ wordColor: INK }));
out(
  path.join(root, 'public/favicon.svg'),
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${MARK.size} ${MARK.size}">${markSvg(GOLD, INK)}</svg>`,
);

// 500 x 500 exports, logo centred with ~12% padding each side
const pad = (lockupW * 0.12) / (1 - 0.24);
const render = (svg) => new Resvg(svg, { fitTo: { mode: 'width', value: 500 } }).render().asPng();
fs.writeFileSync(path.join(brandDir, 'logo-500.png'), render(lockupSvg({ wordColor: WHITE, bg: INK, pad, square: true })));
fs.writeFileSync(path.join(brandDir, 'logo-500-transparent.png'), render(lockupSvg({ wordColor: WHITE, pad, square: true })));

console.log('brand built', { word: [WORD.w, WORD.h], lockup: [lockupW.toFixed(1), lockupH] });
